 .../Api/Admin/AdminGenerationController.php        | 184 [32m++++[m
 .../Controllers/Api/Admin/AnalyticsController.php  | 241 [32m++++++[m
 .../Http/Controllers/Api/Admin/UserController.php  | 131 [32m+++[m
 .../app/Http/Controllers/Api/AuthController.php    | 285 [32m+++++[m[31m--[m
 .../Http/Controllers/Api/GenerationController.php  |  11 [32m+[m
 .../app/Http/Controllers/Api/UploadController.php  |  11 [32m+[m[31m-[m
 backend/app/Services/GenerationService.php         |  78 [32m+[m[31m-[m
 backend/routes/api.php                             |  48 [32m++[m
 frontend/src/App.jsx                               |  40 [32m+[m[31m-[m
 frontend/src/components/layout/DashboardLayout.jsx |  12 [32m+[m[31m-[m
 frontend/src/components/layout/Sidebar.jsx         | 365 [32m++++++[m[31m--[m
 frontend/src/components/layout/Topbar.jsx          | 105 [32m++[m[31m-[m
 frontend/src/context/AuthContext.jsx               |  45 [32m+[m[31m-[m
 frontend/src/index.css                             |  63 [32m+[m[31m-[m
 frontend/src/pages/NotFound.jsx                    |  42 [32m+[m
 frontend/src/pages/admin/AdminAnalytics.jsx        | 518 [32m++++++++++++[m
 frontend/src/pages/admin/AdminApiUsage.jsx         | 530 [32m+++++++++[m[31m---[m
 frontend/src/pages/admin/AdminDashboard.jsx        | 481 [32m++++++++[m[31m---[m
 frontend/src/pages/admin/AdminGenerations.jsx      | 667 [32m+++++++++++++++[m
 frontend/src/pages/admin/AdminModels.jsx           | 923 [32m+++++++++++++++[m[31m------[m
 frontend/src/pages/admin/AdminProviders.jsx        | 713 [32m+++++++++++[m[31m-----[m
 frontend/src/pages/admin/AdminUsers.jsx            | 589 [32m+++++++++++++[m
 frontend/src/pages/dashboard/Dashboard.jsx         | 440 [32m+++++++[m[31m---[m
 frontend/src/pages/dashboard/GenerationDetails.jsx | 509 [32m++++++++[m[31m----[m
 frontend/src/pages/dashboard/History.jsx           | 436 [32m+++++++[m[31m---[m
 frontend/src/pages/settings/Settings.jsx           | 689 [32m+++++++++++++++[m
 26 files changed, 6954 insertions(+), 1202 deletions(-)
